server:
  port: 18081
  compression:
    enabled: true
spring:
  application:
    name: jsy-test-api
  main:
    allow-circular-references: true # 解决sentinel循环依赖
  kafka:
    boostrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}



logging:
  level:
    com.test.apiTest.springboot.channel.openfeign.transfer: DEBUG

